export const GET_EMPLOYEE_TABLE_DATA_REQUEST = "GET_EMPLOYEE_TABLE_DATA_REQUEST";
export const GET_EMPLOYEE_TABLE_DATA_SUCCESS = "GET_EMPLOYEE_TABLE_DATA_SUCCESS";
export const GET_EMPLOYEE_TABLE_DATA_FAILURE = "GET_EMPLOYEE_TABLE_DATA_FAILURE";
export const GET_EMPLOYEE_TABLE_DATA_RESET = "GET_EMPLOYEE_TABLE_DATA_RESET";

export const GET_EMPLOYEE_PROFILE_REQUEST = "GET_EMPLOYEE_PROFILE_REQUEST";
export const GET_EMPLOYEE_PROFILE_SUCCESS = "GET_EMPLOYEE_PROFILE_SUCCESS";
export const GET_EMPLOYEE_PROFILE_FAILURE = "GET_EMPLOYEE_PROFILE_FAILURE";
export const GET_EMPLOYEE_PROFILE_RESET = "GET_EMPLOYEE_PROFILE_RESET";

export const ADD_EMPLOYEE_TABLE_DATA_REQUEST = "ADD_EMPLOYEE_TABLE_DATA_REQUEST";
export const ADD_EMPLOYEE_TABLE_DATA_SUCCESS = "ADD_EMPLOYEE_TABLE_DATA_SUCCESS";
export const ADD_EMPLOYEE_TABLE_DATA_FAILURE = "ADD_EMPLOYEE_TABLE_DATA_FAILURE";
export const ADD_EMPLOYEE_TABLE_DATA_RESET = "ADD_EMPLOYEE_TABLE_DATA_RESET";

export const EDIT_EMPLOYEE_TABLE_DATA_REQUEST = "EDIT_EMPLOYEE_TABLE_DATA_REQUEST";
export const EDIT_EMPLOYEE_TABLE_DATA_SUCCESS = "EDIT_EMPLOYEE_TABLE_DATA_SUCCESS";
export const EDIT_EMPLOYEE_TABLE_DATA_FAILURE = "EDIT_EMPLOYEE_TABLE_DATA_FAILURE";
export const EDIT_EMPLOYEE_TABLE_DATA_RESET = "EDIT_EMPLOYEE_TABLE_DATA_RESET";

export const DELETE_EMPLOYEE_TABLE_DATA_REQUEST = "DELETE_EMPLOYEE_TABLE_DATA_REQUEST";
export const DELETE_EMPLOYEE_TABLE_DATA_SUCCESS = "DELETE_EMPLOYEE_TABLE_DATA_SUCCESS";
export const DELETE_EMPLOYEE_TABLE_DATA_FAILURE = "DELETE_EMPLOYEE_TABLE_DATA_FAILURE";
export const DELETE_EMPLOYEE_TABLE_DATA_RESET = "DELETE_EMPLOYEE_TABLE_DATA_RESET";